/**
 * This file is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This file implements the functions for encoding and decoding the
 * 'sensor_msg' message type. See tgx_serial_msg.h for more details.
 */

#include <message.h>
#include "tgx_serial_msg.h"

uint16_t sensor_msg_nodeId_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 0, 16);
}

void sensor_msg_nodeId_set(tmsg_t *msg, uint16_t value)
{
  tmsg_write_ube(msg, 0, 16, value);
}

uint16_t sensor_msg_parentId_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 16, 16);
}

void sensor_msg_parentId_set(tmsg_t *msg, uint16_t value)
{
  tmsg_write_ube(msg, 16, 16, value);
}

uint16_t sensor_msg_position_x_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 32, 16);
}

void sensor_msg_position_x_set(tmsg_t *msg, uint16_t value)
{
  tmsg_write_ube(msg, 32, 16, value);
}

uint16_t sensor_msg_position_y_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 48, 16);
}

void sensor_msg_position_y_set(tmsg_t *msg, uint16_t value)
{
  tmsg_write_ube(msg, 48, 16, value);
}

uint16_t sensor_msg_sensor_temp_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 64, 16);
}

void sensor_msg_sensor_temp_set(tmsg_t *msg, uint16_t value)
{
  tmsg_write_ube(msg, 64, 16, value);
}

uint16_t sensor_msg_sensor_photo_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 80, 16);
}

void sensor_msg_sensor_photo_set(tmsg_t *msg, uint16_t value)
{
  tmsg_write_ube(msg, 80, 16, value);
}

uint16_t sensor_msg_sensor_sound_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 96, 16);
}

void sensor_msg_sensor_sound_set(tmsg_t *msg, uint16_t value)
{
  tmsg_write_ube(msg, 96, 16, value);
}

uint16_t sensor_msg_sensor_x_acc_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 112, 16);
}

void sensor_msg_sensor_x_acc_set(tmsg_t *msg, uint16_t value)
{
  tmsg_write_ube(msg, 112, 16, value);
}

uint16_t sensor_msg_sensor_y_acc_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 128, 16);
}

void sensor_msg_sensor_y_acc_set(tmsg_t *msg, uint16_t value)
{
  tmsg_write_ube(msg, 128, 16, value);
}

uint16_t sensor_msg_sensor_x_mag_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 144, 16);
}

void sensor_msg_sensor_x_mag_set(tmsg_t *msg, uint16_t value)
{
  tmsg_write_ube(msg, 144, 16, value);
}

uint16_t sensor_msg_sensor_y_mag_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 160, 16);
}

void sensor_msg_sensor_y_mag_set(tmsg_t *msg, uint16_t value)
{
  tmsg_write_ube(msg, 160, 16, value);
}

uint16_t sensor_msg_crc_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 176, 16);
}

void sensor_msg_crc_set(tmsg_t *msg, uint16_t value)
{
  tmsg_write_ube(msg, 176, 16, value);
}

