/**
 * This file is automatically generated by ncg. DO NOT EDIT THIS FILE.
 * It includes values of some nesC constants from
 * tgx.h.
 */

enum {
    SERIAL_DEFAULT_SEND_PERIOD = 1000,
    SERIAL_AM_SENSOR_MSG = 43,
    SERIAL_SENSOR_RANGE_MIN_Y = 0,
    SERIAL_AM_CONTROL_MSG = 42,
    SERIAL_SENSOR_RANGE_MAX_Y = 1000,
    SERIAL_SENSOR_READ_COUNT = 7,
    SERIAL_DESSMINATE_KEY = 44,
    SERIAL_SENSOR_RANGE_MAX_X = 1000,
    SERIAL_SENSOR_RANGE_MIN_X = 0,
    SERIAL_DEFAULT_SENSOR_PERIOD = 100
};
