#!/bin/bash

# @author: van9ogh
# @email: van9ogh@gmail.com
# @ChangeLog: 2012/09/03 22:00


# 本脚本用来测试tinyos-web程序有没有内存泄露问题
# 执行完后会删除TOSEngine生成的两个文件
cd ../bin
valgrind --tool=memcheck --leak-check=full --show-reachable=yes --track-fds=yes ./tinyos-graphics
#rm -rf tinyos-graphics*
